package com.example.notesapproom.enums

enum class SortOptions {
    TITLE_ASCENDING,
    TITLE_DESCENDING,
    DATE_MODIFIED_OLDEST_FIRST,
    DATE_MODIFIED_NEWEST_FIRST,
    DATE_CREATED_OLDEST_FIRST,
    DATE_CREATED_NEWEST_FIRST;
}